### ISSUE TITLE
Using CapyCon with Poltergeist (PhantomJS)

### ISSUE THREAD

**Issue by nmindz** [gunesmes/capycon#1]
Could not really find anything related to use CapyCon with PhantomJS/Poltergeist. Would that be possible?

I'm having a weird bug with DNS resolving but only when using Poltergeist, not PhantomJS alone, so I was trying to debug from IRB/Pry but I'm also new to Ruby so I'd take any hint/advice with a smile.

Found CapyCon and from using it with Chrome and the available drivers listed upon launch, it works perfectly. However, like I said, I'd like to test that with PhantomJS. Is there support/a way to do that?

**Comment by gunesmes** [comment]
Thanks for using CapyCon,

Phantomjs has not been supported since 2017. You can check [this tread](https://groups.google.com/g/phantomjs/c/9aI5d-LDuNE/m/5Z3SMZrqAQAJ). If you have not switched to Chrome headless in your project, you can still use phantomjs in the console, run the following command additionally in CapyCon: 

```ruby
# import required lib
require 'capybara/poltergeist'

# create Poltergeist driver
 Capybara.register_driver :poltergeist do |app|
   Capybara::Poltergeist::Driver.new(app, options)
 end

# set the default javascript with Poltergeist driver
Capybara.javascript_driver = :poltergeist

# open browser by visiting target URL
visit "http://testrisk.com/" 
```

be sure that Poltergeist uses the Phantomjs as the driver so it needs to be available in your path.

**Comment by nmindz** [comment]
Yeah, I came late to the party. Just realized today that PhantomJS has actually been halted indefinitely. But thanks for the heads up! 🙂

All I need is a actually a Capybara driver that supports authenticated proxies (changing settings on the fly would be nice, but not required) and I realized my problems actually came out of the sheer fact that PhantomJS could not render the website properly, because of ES6 JavaScript, therefore it just failed erratically.

Do you know of any Capybara driver that is JavaScript capable and supports authenticated proxies? I know this has nothing really to do with CapyCon itself, but from your answer I'm actually gonna adapt it for other use cases. Once again, thanks!

**Comment by gunesmes** [comment]
You can use chromedriver as well see the document for setting proxy: https://chromedriver.chromium.org/capabilities
